### ISSUE TITLE
`jwt.ValidationErrorIssuedAt` ignored at significant peril

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry-incubator/uaa-go-client#15]
`DecodeToken()` current swallows a `jwt.ValidationErrorIssuedAt` error.

It's not clear why - perhaps to avoid clock skew issues with tokens issued slightly in the future?

Regardless - this error swallowing is incredibly brittle. The docs for `jwt.Parse()` simply state that: `If everything is kosher, err will be nil`

Consider an optimization to the JWT library whereby they may decide to validate the issued at time *before* checking the token signature. In such as case they would return this same error, even if the token wasn't signed by UAA, and this code would accept it.

It might be better to simply not swallow this error. If clock skew is an issue, perhaps have UAA fudge a slightly earlier issued at time to begin with?

@drnic as fyi

**Comment by aeijdenberg** [comment]
see also https://github.com/dgrijalva/jwt-go/issues/246

**Comment by zachgersh** [comment]
@aeijdenberg - the discussion there is explicitly WHY we are swallowing the error. Since we are in control of bumping the jwt library dependency we can always bring it back in the case that the error does mean something in the future but as suggested in the issue you linked - that field just doesn't matter.

Also, we discussed the idea of issuing tokens in the future and that was not something UAA wanted to pursue at this time.

**Comment by aeijdenberg** [comment]
@zachgersh - in 12 months time, when someone else in your team is running `dep ensure -update` across your project in order to pick up a security fix from one of your libraries, what processes do you have in place to ensure that that person specifically reads the source code for this particular dependency to ensure that the undocumented behavior that you currently relying on (for a security feature) is still correct? If the answer is none, then I don't think it's fair to mark this issue as closed.

Further, as this project is designed to be used as a library (and at a quick glance, I don't think it actually locks dependencies at all), I'm not sure your comment holds?

**Comment by zachgersh** [comment]
@aeijdenberg - I hope / plan to actually deprecate this library in the near term (this ticket is now making me want to pick that work back up again). 

This is a library and due to the unfortunate way that golang interacts with dependencies - the vendoring details are in the actual routing-release where this project is included (note this is not using dep or a go.mod):

https://github.com/cloudfoundry/routing-release/tree/develop/src/github.com/dgrijalva

I think we are currently comfortable with the information presented by the library authors of the fact that we have no security related reason to validate that field.

**Comment by aeijdenberg** [comment]
@zachgersh - it would be better to have no library than a brittle, [poorly documented](https://github.com/cloudfoundry-incubator/uaa-go-client/issues/13) and [broken during key rotation](https://github.com/cloudfoundry-incubator/uaa-go-client/issues/14) library, so yeah, maybe grab that ticket and kill this already. That may sound harsh, but a library to provide security features needs to be of a high standard - it would be better to not exist than to exist and not work as expected.

I still think though that you're misunderstanding a subtle point that I'll reiterate one more time in case it helps with design of any successor library in the future. Even if this particular field is not one that you care about validating for any security reason, there are other fields that you do care about (and other security properties such as actually having a valid signature).

The API that you're calling on the JWT library does not guarantee it will return all errors, nor does it guarantee any order of checking security properties. It just says that it will return no errors, if everything (the set of what you care about and what you don't care about) is OK. That means that a client of the JWT library simply cannot make the choice to ignore any particular error, as there will be no guarantee that the other properties that it cares about have been checked prior to that error being returned.
